import { WeekPlan, DayPlan } from '../types';

export const WEEKLY_STRUCTURE: DayPlan[] = [
  {
    day: 'monday',
    dayName: 'Lunes',
    sessionType: 'running_threshold',
    title: 'Running Umbral',
    duration: 60,
    description: 'Rodaje a ritmo de umbral aeróbico con series de calidad',
    warmup: '15 min trote suave + activación dinámica',
    cooldown: '10 min trote suave + estiramientos',
    exercises: [
      {
        id: 'mon-1',
        name: 'Calentamiento',
        duration: '15 min',
        notes: 'Trote suave z1-z2',
      },
      {
        id: 'mon-2',
        name: 'Series de umbral',
        reps: '4x8 min',
        rest: '2 min entre series',
        notes: 'Ritmo z3-z4, esfuerzo controlado 7/10',
      },
      {
        id: 'mon-3',
        name: 'Enfriamiento',
        duration: '10 min',
        notes: 'Trote suave z1',
      },
    ],
    notes: 'RPE objetivo 7/10. Si hay fatiga acumulada, bajar a ritmo fácil.',
  },
  {
    day: 'tuesday',
    dayName: 'Martes',
    sessionType: 'swimming',
    title: 'Natación Técnica',
    duration: 45,
    description: 'Sesión de natación enfocada en técnica y resistencia aeróbica',
    warmup: '200m crol suave',
    cooldown: '100m espalda relajada',
    exercises: [
      {
        id: 'tue-1',
        name: 'Calentamiento',
        distance: '200m',
        notes: 'Crol suave, foco en respiración',
      },
      {
        id: 'tue-2',
        name: 'Drill técnico',
        reps: '6x50m',
        rest: '20s',
        notes: 'Catch-up drill, dedos al cielo',
      },
      {
        id: 'tue-3',
        name: 'Bloque principal',
        reps: '8x100m',
        rest: '30s',
        notes: 'Ritmo aeróbico constante, z2-z3',
      },
      {
        id: 'tue-4',
        name: 'Vuelta a la calma',
        distance: '100m',
        notes: 'Espalda relajada',
      },
    ],
    notes: 'Foco en posición horizontal y entrada de mano. Sin forzar ritmo.',
  },
  {
    day: 'wednesday',
    dayName: 'Miércoles',
    sessionType: 'gym_strength',
    title: 'Fuerza + Movilidad',
    duration: 70,
    description: 'Sesión de gimnasio: fuerza funcional para running y Hyrox',
    warmup: '10 min cardio suave + activación articular',
    cooldown: 'Foam roller + estiramientos 10 min',
    exercises: [
      {
        id: 'wed-1',
        name: 'Sentadilla búlgara',
        sets: 4,
        reps: '8 por lado',
        load: '20-30 kg mancuernas',
        rest: '90s',
      },
      {
        id: 'wed-2',
        name: 'Peso muerto rumano',
        sets: 4,
        reps: '10',
        load: '60-80% 1RM',
        rest: '90s',
      },
      {
        id: 'wed-3',
        name: 'Hip thrust',
        sets: 3,
        reps: '12',
        load: 'Moderado',
        rest: '75s',
      },
      {
        id: 'wed-4',
        name: 'Step-ups con carga',
        sets: 3,
        reps: '10 por lado',
        load: '15-20 kg mancuernas',
        rest: '60s',
      },
      {
        id: 'wed-5',
        name: 'Core: Pallof press',
        sets: 3,
        reps: '12 por lado',
        rest: '45s',
      },
      {
        id: 'wed-6',
        name: 'Core: Dead bug',
        sets: 3,
        reps: '10 por lado',
        rest: '45s',
      },
    ],
    notes: 'Técnica sobre carga. Si hay agujetas de lunes, reducir intensidad.',
  },
  {
    day: 'thursday',
    dayName: 'Jueves',
    sessionType: 'running_intervals',
    title: 'Intervalos VO2max',
    duration: 55,
    description: 'Series cortas a alta intensidad para desarrollar VO2max',
    warmup: '15 min progresivo',
    cooldown: '10 min suave',
    exercises: [
      {
        id: 'thu-1',
        name: 'Calentamiento progresivo',
        duration: '15 min',
        notes: 'z1→z2→z3, últimos 2 min con 4 aceleraciones de 20s',
      },
      {
        id: 'thu-2',
        name: 'Series VO2max',
        reps: '6x3 min',
        rest: '3 min trote suave',
        notes: 'Ritmo 5km race pace. z5. Esfuerzo 9/10',
      },
      {
        id: 'thu-3',
        name: 'Enfriamiento',
        duration: '10 min',
        notes: 'Trote muy suave z1',
      },
    ],
    notes: 'Si las series salen muy fáciles, añadir 1-2 más. Si hay fatiga, reducir a 4x3.',
  },
  {
    day: 'friday',
    dayName: 'Viernes',
    sessionType: 'gym_hyrox',
    title: 'Hyrox Circuit',
    duration: 65,
    description: 'Entrenamiento funcional Hyrox: ski erg, sled, wall balls, burpees',
    warmup: '10 min cardio + movilidad',
    cooldown: 'Estiramientos globales 10 min',
    exercises: [
      {
        id: 'fri-1',
        name: 'Ski Erg',
        distance: '1000m',
        notes: 'Ritmo constante, técnica correcta. Objetivo <4:30',
      },
      {
        id: 'fri-2',
        name: 'Sled Push',
        distance: '50m x4',
        load: '60-80 kg',
        rest: '90s',
        notes: 'Postura baja, empuje desde piernas',
      },
      {
        id: 'fri-3',
        name: 'Burpee Broad Jump',
        reps: '20',
        notes: 'Explosivo, buen salto horizontal',
      },
      {
        id: 'fri-4',
        name: 'Wall Balls',
        reps: '50',
        load: '6 kg',
        notes: 'Target a 9 pies. Sin parar si es posible',
      },
      {
        id: 'fri-5',
        name: 'Remo ergómetro',
        distance: '500m x3',
        rest: '2 min',
        notes: 'Potencia + técnica, objetivo <2:00/500m',
      },
      {
        id: 'fri-6',
        name: 'Farmer Carry',
        distance: '100m x3',
        load: '24 kg por mano',
        rest: '90s',
        notes: 'Hombros atrás, paso firme',
      },
    ],
    notes: 'Registrar tiempos para seguimiento de progresión.',
  },
  {
    day: 'saturday',
    dayName: 'Sábado',
    sessionType: 'running_long',
    title: 'Tirada Larga',
    duration: 100,
    description: 'Rodaje largo de resistencia aeróbica base para media maratón',
    warmup: '10 min muy suave',
    cooldown: '10 min andando + estiramientos',
    exercises: [
      {
        id: 'sat-1',
        name: 'Calentamiento',
        duration: '10 min',
        notes: 'Andar → trote muy suave',
      },
      {
        id: 'sat-2',
        name: 'Rodaje largo',
        duration: '75-90 min',
        notes: 'z2 constante. Conversación posible. 5:30-6:00 min/km aprox.',
      },
      {
        id: 'sat-3',
        name: 'Vuelta a la calma',
        duration: '10 min',
        notes: 'Reducir ritmo gradualmente. Andar último km.',
      },
    ],
    notes: 'Hidratación cada 20-25 min. Geles a partir de 60 min. Nunca superar z3.',
  },
  {
    day: 'sunday',
    dayName: 'Domingo',
    sessionType: 'active_recovery',
    title: 'Recuperación Activa',
    duration: 30,
    description: 'Día de recuperación: movilidad, natación suave o paseo',
    exercises: [
      {
        id: 'sun-1',
        name: 'Foam roller',
        duration: '10 min',
        notes: 'Cuádriceps, isquios, gemelos, IT band',
      },
      {
        id: 'sun-2',
        name: 'Movilidad hip',
        reps: '5 por lado',
        notes: 'World greatest stretch, 90/90, pigeon pose',
      },
      {
        id: 'sun-3',
        name: 'Yoga / respiración',
        duration: '15 min',
        notes: 'Opcional. Foco en sistema nervioso parasimpático',
      },
    ],
    notes: 'Descanso mental también. Evitar pensar en entrenamientos.',
  },
];

export const BASE_WEEK: WeekPlan = {
  week: 1,
  phase: 'base',
  focus: 'Construir base aeróbica y adaptación al volumen',
  days: WEEKLY_STRUCTURE,
};

export const TRAINING_PHASES = {
  base: { weeks: [1, 2, 3, 4], focus: 'Base aeróbica' },
  build: { weeks: [5, 6, 7, 8], focus: 'Construcción de volumen e intensidad' },
  peak: { weeks: [9, 10, 11, 12], focus: 'Pico de forma' },
  taper: { weeks: [13, 14], focus: 'Descarga para la carrera' },
  race: { weeks: [15], focus: 'Semana de carrera' },
  hyrox_prep: { weeks: [16, 17, 18, 19, 20], focus: 'Preparación Hyrox' },
} as const;

export const SESSION_COLORS: Record<string, string> = {
  running_easy: '#30D158',
  running_threshold: '#0A84FF',
  running_long: '#5AC8FA',
  running_intervals: '#FF453A',
  swimming: '#64D2FF',
  gym_strength: '#BF5AF2',
  gym_hyrox: '#FF9F0A',
  hyrox_simulation: '#FF6B35',
  rest: '#48484A',
  active_recovery: '#32D74B',
};

export const SESSION_LABELS: Record<string, string> = {
  running_easy: 'Running Suave',
  running_threshold: 'Umbral',
  running_long: 'Tirada Larga',
  running_intervals: 'Intervalos',
  swimming: 'Natación',
  gym_strength: 'Fuerza',
  gym_hyrox: 'Hyrox',
  hyrox_simulation: 'Simulación Hyrox',
  rest: 'Descanso',
  active_recovery: 'Recuperación',
};
